spring:
  profiles:
    active: druid
    include: shiro,reids
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    servlet:
      content-type: text/html
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.cctv.project.noah.**.entity
server:
  port: 80
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



wechat:
  appId: wx7c50afe98b079964
  appSecret: a60a96116250a18cabc462d46166f788
  token: 71d9eaedec314f6e84d45c926d9b9706
  userName: gh_01c7874bac25